### PR TITLE
[WIP] Handle globbing, clean up arguments

### PR DESCRIPTION
**Pull request by johnotander**
Related to #12 

I propose modifying the arguments/API to something like:

```js
immutableCss({
  immutableCss: 'vendor/basscss.css',
  customCss: 'app/**/*.css',
  verbose: true,
  ignoredSelectors: ['.button']
}, function(mutations) {
  // mutations is an array of mutation objects
  // [{
  //   selector: '.foobar',
  //   line: 123,
  //   column: 1,
  //   rule: rule // => PostCSS rule object
  // },{
  // ... ]
});
```

## TODO

- [x] Glob support
- [x] Add globbing specific tests
- [x] Update the documentation
- [ ] Add an option to compare amongst app css files (#12)

### CODE REVIEW

**Comment by johnotander** [comment]
Do you have any more thoughts on what terminology we want to use, @jxnblk ? Currently, I'm interchanging immutable/vendor and app/custom haphazardly. I suspect at some point this week I'll have a `1.0` ready to go, so I imagine we should probably iron out what the best terminology is so I can update the documentation/options/variables to reflect it. However, I'm having a hell of a time figuring out which terms are most descriptive.

Any insight here would be greatly appreciated.

**Comment by jxnblk** [comment]
Yeah I've been thinking about the language as well. Feels like a mental blocker for me...

In going to re-read a few articles for research, then put together a long list of potential words to maybe help us out.

**Comment by johnotander** [comment]
Awesome, :heart_eyes_cat: . Do you mind linking some of the articles you're reading if you get a chance? I'd love to absorb some more content relating to the immutability in CSS.

**Comment by johnotander** [comment]
After some consideration and discussion, I've decided to add this functionality to a standalone CLI. This will ensure that this module remains as simple as possible.

**Pull request closed without merging**
